### ISSUE TITLE
Adjust to Client classes no longer implementing serializable. 

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/flink-connectors#137]
**Problem description**
Per the discussion in #2589

> We'll need to adjust the Flink connector's hook accordingly. Flink has a SimpleVersionedSerializer interface that is relevant here:
https://ci.apache.org/projects/flink/flink-docs-release-1.4/api/java/org/apache/flink/core/io/SimpleVersionedSerializer.html
>For reference, here's the hook interface, which our connector implements (see createCheckpointDataSerializer):
https://ci.apache.org/projects/flink/flink-docs-release-1.4/api/java/org/apache/flink/runtime/checkpoint/MasterTriggerRestoreHook.html

**Problem location**
Classes interacting with Checkpoints

**Suggestions for an improvement**
We should create a general class for dealing with classes that implement toBytes()/fromBytes() as opposed to java serialization.

**Comment by vijikarthi** [comment]
The https://github.com/pravega/flink-connectors/blob/master/src/main/java/io/pravega/connectors/flink/CheckpointSerializer.java implementation uses `toBytes()` and `fromBytes()` implementation of `CheckpointImpl` to serialize and deserialize the checkpoint instance. The `CheckpointImpl` itself could evolve over a period of time and hence its `version` and `revision` numbers could change.

Since the `CheckpointSerializer` has its own way to track the revisions (version numbers) https://github.com/pravega/flink-connectors/blob/master/src/main/java/io/pravega/connectors/flink/CheckpointSerializer.java#L26, any revision to the `CheckpointImpl` will be taken care by `CheckpointSerializer.VERSION` (assuming we update `CheckpointSerializer.VERSION`  whenever `CheckpointImpl` revision happens) and I am thinking that we don't need to make any further changes to the current implementation?

**Comment by EronWright** [comment]
When I wrote the original comment, I didn't realize that we already had a serializer in place.   I agree there's nothing left to do.  

The version number is an interesting issue.  In some sense they are independent, but revving one with the other would have the following beneficial behavior: in case of a version mismatch, Flink would know upfront that the versions don't match.  Otherwise we would simply get a Pravega `SerializationException`.   But I agree that we could keep them synced by hand.
