### ISSUE TITLE
Executor service in `FlinkPravegaWriter`

### ISSUE THREAD

**Issue by fpj** [pravega/flink-connectors#157]
**Problem description**
I'm wondering whether the executor service created in `FlinkPravegaWriter` is really necessary. Please refer to this comment here:

https://github.com/pravega/flink-connectors/pull/156#discussion_r196889995

**Problem location**
`FlinkPravegaWriter`

**Suggestions for an improvement**
Do not create a new executor service and use the default thread pool.

**Comment by EronWright** [comment]
My rationale for why it makes sense to isolate the write callbacks in a thread pool that we control:

The Flink TaskManager is the Java process that executes the tasks of a Flink job.   Over time, numerous jobs execute in the task manager.  It is the responsibility of the task to cleanup its resources, avoid leaks, otherwise the TaskManager will gradually degrade.

By executing the write callbacks in a thread pool that we control, the connector is able to effectively cleanup after itself by closing the executor service.

**Comment by elizabethbain** [comment]
@fpj 
I talked with Vijay about this and with Eron earlier. They had thought using the executor thread for the response was the best approach in determining where the future returns in that it gives the client the control of the life cycle of the thread rather than leaving the control in the task manager. It allows the client to ensure the thread resources are cleaned up after they are no longer needed.  
   I wanted to get your perspective on why leaving it with the task manager might be preferable.

**Comment by fpj** [comment]
@elizabethbain I don't have a strong position on the matter. I feel that it is better to create threads (and pools) only when strictly necessary to avoid hogging the CPU, but this singleton thread pool does not seem to be causing trouble. Consequently, there is no strong reason to remove it.

I didn't understand the comment about the task manager, though. My suggestion was to rely on the common thread pool.

**Comment by elizabethbain** [comment]
close 157 based on comments from stakeholders

**Comment by vijikarthi** [comment]
closing the issue as we have decided to leave the current implementation as-is.
