### ISSUE TITLE
Add test cases for checkpoint timeouts

### ISSUE THREAD

**Issue by crazyzhou** [pravega/flink-connectors#264]
**Problem description**
To verify PravegaReader checkpoint can succeed after timeouts, we should add test cases.

**Problem location**
tests

**Suggestions for an improvement**

**Comment by maddisondavid** [comment]
The default for a checkpoint timeout is currently 5 seconds which, if everything is going well, should be enough time for all the checkpoint events to pass through the readers.  During testing however we have seen cases where checkpoints have timed out due to environmental issues such as networking problems.

Personally it seems like this is application/environment specific and interplays with whatever the configured checkpointing interval is.  Since the user can tune this timeout with `withCheckpointInitiateTimeout` when building the `FlinkPravegaReader` would we consider a default of 5 seconds to be adequate?

**Comment by crazyzhou** [comment]
You are right. @vijikarthi also think it no need to fix. But we can add test cases for it to verify no checkpoint is stuck in spite of timeouts.

**Comment by crazyzhou** [comment]
Fixed by #283
