### ISSUE TITLE
Fix build warnings

### ISSUE THREAD

**Issue by fpj** [pravega/flink-connectors#370]
**Problem description**
There are a number of warnings that need to be fixed, I'm posting them in a txt file attached.

**Problem location**
Build warnings.

**Suggestions for an improvement**
Fix the code to eliminate the warnings.

[flink-connector-warnings.txt](https://github.com/pravega/flink-connectors/files/4593333/flink-connector-warnings.txt)

**Comment by crazyzhou** [comment]
There is an issue #237 for this, I also pay attention to this along the implementation. I have already taken effort to eliminate some in the 1.10 upgrade and more (mainly in Table API methods) is done in this PR #363 , but there are still one thing we can't easily upgrade that is the `BatchTableSource` and `BatchTableSink`. Here are some reasons.

1. These APIs are deprecated because the Blink planner is unifying the Batch into the Stream. The suggested change is to use `InputFormatTableSource` and `OutputFormatTableSink` which is an extention of `StreamTableSource/Sink` and still marked experimental.
2. I cannot directly change to use the new API, because we rely on the batch table factory https://github.com/pravega/flink-connectors/blob/master/src/main/java/io/pravega/connectors/flink/FlinkPravegaBatchTableSourceFactory.java#L38 which needs to give out a `BatchTableSource/Sink`. There is another issue #356 for this change entirely.
3. These APIs are still used in the Flink code. https://github.com/apache/flink/blob/master/flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/sinks/CsvTableSink.java#L41 
4. As a bigger picture, I'm going to rush on #356 because the whole [FLIP-32](https://cwiki.apache.org/confluence/display/FLINK/FLIP-32%3A+Restructure+flink-table+for+future+contributions) is still in progress. And soon, it will have a new structure of the table API. (ref. [FLIP-95](https://cwiki.apache.org/confluence/display/FLINK/FLIP-95%3A+New+TableSource+and+TableSink+interfaces)). It will be better to wait the final interfaces ready on Flink side first.
