### ISSUE TITLE
Implement batch connector (source only)

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#42]
**Problem description**
Develop a batch connector to process historical data in a given stream using the Flink Batch API.  A good reason is to be able to use Flink Gelly (graph API) and Flink ML which are based on the batch API.

It is probably sufficient to consider a Pravega stream as a _source_, not as a _sink_, for batch purposes.

**Suggestions for an improvement**
_There's at least two approaches being considered.  One is to treat segments as splits, which seems more likely to leverage data locality and more compatible with fine-grained recovery, but requires client changes.  Another is to synthesize a split per subtask and to use the existing reader group API, which would require fewer changes to the Pravega client but underperform at scale._

Implement an `InputFormat`, which splits an input file or other resource (e.g. Pravega stream) into processable units for Flink to process across a number of subtask instances.  For example, a file-based input format splits the input file(s) into splits representing non-overlapping ranges that correspond to HDFS blocks.    For Pravega, a close analogue would be to treat each segment as an input split.

If location hints are available (on a per-split basis), implement `LocatableInputSplit` and return an instance of `LocatableInputSplitAssigner` from `InputFormat`.

A connector is free to read each split in whatever way it chooses.  It needn't be a file-based access.  For example, if each segment were a split, the connector could use a Pravega Reader API to query a specific segment, e.g. `io.pravega.client.segment.impl.SegmentInputStream` (which the reader group API uses under the hood).

**Comment by EronWright** [comment]
@StephanEwen @fpj In our recent discussion, it was suggested that the existing reader group API be used for batch processing.   Despite its benefits, one concern I have is that it might underperform relative to the segment processing approach, due to the ordering guarantee that the reader group normally provides but isn't (to my knowledge) useful here.    Imagine a stream that has, on average, ten segments covering the keyspace at any given point in time.  There might be hundreds or thousands of segments in the stream as a whole, but scaling the subtasks beyond ten would yield diminishing returns because subtasks would sit idle.  In other words, the scheduling of segments would be overly conservative.

**Comment by EronWright** [comment]
(A visualization to complement my above comment)
![pravega stream viz](https://user-images.githubusercontent.com/1775518/30716032-4f3ff620-9ecd-11e7-8f95-2a3fa378f1b4.png)

**Comment by fpj** [comment]
@EronWright 

> Imagine a stream that has, on average, ten segments covering the keyspace at any given point in time. There might be hundreds or thousands of segments in the stream as a whole, but scaling the subtasks beyond ten would yield diminishing returns because subtasks would sit idle waiting for assignments.

Correct, if you don't care about the order of events, then following the sequence of segments established by the scaling events will reduce the degree of parallelism unnecessarily, and consequently will increase processing time. 

> treat segments as splits, which seems more likely to leverage data locality

I think there are a couple of implicit suggestions here. The first one is that we don't need to follow any specific order for the segments in the case of batch processing. As such, the maximum degree of parallelism when processing the stream data is given by the cardinality of the set of segments, and otherwise, the source workers are free to process segments in any order they like.

The second suggestion is that by not having to follow any order, the sources can read raw segment data directly. I think data locality here is referring to the ability of reading from a node nearby rather than having to go somewhere else to request the data.

Assuming that the stream is sealed, there is no change to the stream data or set of segments of the stream. As such, and assuming that order isn't important, it sounds right the observation that we can process the segments in parallel. It should be possible for us to implement a different flavor of reader groups that ignores order and coordinates the reading of segments. In the case that there is no rebalance (a given reader reads any segment it is assigned entirely), it shouldn't be difficult. I wouldn't change the functionality of the existing reader group, though.

As for reading raw data directly, I'm less excited about that because it breaks one of the nice features of pravega, which is having a unified API for stream and batching. I'm also concerned about correctness. We don't necessarily guarantee that the data in Tier 2 is consistent when reading it raw. The segment store logic is responsible for making sense of that data and guaranteeing that it is consistent, but we don't guarantee that we won't have spurious files, and possibly even duplicates in there.

> ... and more compatible with fine-grained recovery

I think this is saying that because sources only read segments entirely, recover is simple because we can rollback to the beginning of the segments that a recovering source was previously processing. For example, if a source _S_ is processing segments _T1_ and _T2_, and we decide to recover it (say it crashed), then all we need to do is resume from the beginning of _T1_ and _T2_, assuming that the partial data generated downstream as part of processing these segments can be discarded.

**Comment by EronWright** [comment]
I believe that @fpj in the above comments took the assumption that the segments would be accessed directly on Pravega's tier-2 storage backend.  I revised the description to clarify the suggestion to the effect that segments would be accessed via Pravega's frontend not via tier-2.

Meanwhile, on the topic of locality, I think the concept is mostly related to the cost of accessing a particular segment.  Since Flink has some flexibility as to where to schedule the compute associated with a given segment or stream, it makes sense to strive for the cheapest location based on Pravega's architecture and whatever hints it may provide.

**Comment by EronWright** [comment]
Thanks @tzulitai !
