### ISSUE TITLE
Migrate the integration tests to use testcontainer

### ISSUE THREAD

**Issue by crazyzhou** [pravega/flink-connectors#459]
**Problem description**
[Testcontainer](https://www.testcontainers.org/) is a nice tool to have a small dockerized pravega running for testing.
Flink community is also trying to introduce the connector test framework with this in [FLINK-19554](https://issues.apache.org/jira/browse/FLINK-19554)
This needs to be investigated.

**Problem location**
Integration tests

**Suggestions for an improvement**

**Comment by derekm** [comment]
Correct usage of Pravega with testscontainers can be found here: https://github.com/debezium/debezium/blob/master/debezium-server/debezium-server-pravega/src/test/java/io/debezium/server/pravega/PravegaTestResource.java#L37

Using deprecated `FixedHostPortGenericContainer` is required due to https://github.com/pravega/pravega/issues/6060
