### ISSUE TITLE
Treat Pravega as a source dependency

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#88]
**Problem description**
Fix the travis build of the connector to build Pravega automatically, so that the connector may be unit tested by travis.

**Suggestions for an improvement**
Consider using a submodule plus a [composite build](https://docs.gradle.org/current/userguide/composite_builds.html) to incorporate the Pravega build into the connector build.

**Comment by fpj** [comment]
@EronWright I have a few of questions about this issue:
- The travis build is failing because it is looking for 0.3.0-SNAPSHOT, so I think you are trying to address that. Is it necessary that connectors master relies on pravega master, or should we make the connectors depend on the latest released? I can't remember whether we have come to a conclusion about that.
- Would it be optional to build Pravega from source with the changes in PR #98?
- How would it work with releases? For a release of the connectors, it would be good to make sure they depend on a specific version of Pravega.

**Comment by EronWright** [comment]
@fpj I agree there's a big decision point here about how closely coupled the connector should be.   

I made it so that the `pravegaVersion` variable determines the behavior; release versions of Pravega are pulled from Maven while snapshots are built from the submodule.  

Honestly I don't know how this approach will pan out, an in particular how it will cooperate with shading of Pravega.   At the moment it seems to work nicely.
